apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bblt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-bblt@sha256:1dd8790a1ade994b5881c2e12d94ec616d50c2b61b9a39fcaf6ed0f0d15ec628
        name: my-nodejs
        resources: {}
status: {}
